name: Deploy to AWS

on:
  push:
    branches:
      - main  # Define el branch que activará el flujo de trabajo, normalmente 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Especifica la versión de Node.js

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test  # Opcional, si tienes pruebas automatizadas

    - name: Deploy to AWS
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1' 
      run: |
        npm run build   # Ejecuta tu script de construcción si tienes uno
        # Usa AWS CLI o un script para desplegar tu app
