name: Deploy to AWS Lambda

on:
  push:
    branches:
      - falon

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  
        
      - name: Set up Node.js
        uses: actions/setup-node@v3  
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
        working-directory: ./backend

      - name: Zip the function
        run: zip -r function.zip src node_modules
        working-directory: ./backend

      - name: Deploy to Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-west-2
        run: |
          aws lambda update-function-code --function-name fittrack-backend-function --zip-file fileb://function.zip
        working-directory: ./backend
